### ISSUE TITLE
Crash with LiteLoader

### ISSUE THREAD

**Issue by Ecdcaeb** [CleanroomMC/MixinBooter#65]
Should we solve the crash, or toast a window that says "You cannot use A and B together" to notice the player.
Issue https://github.com/Ecdcaeb/Custom-Colorful-Enchantment/issues/1

**Comment by Rongmario** [comment]
Liteloader has its own entrypoint, I haven't had the time to look into this, but liteloader on 1.12.2 is quite impossible to properly run in a normal modpack already.

**Comment by HowardZHY** [comment]
> Should we solve the crash, or toast a window that says "You cannot use A and B together" to notice the player. Issue [Ecdcaeb/Custom-Colorful-Enchantment#1](https://github.com/Ecdcaeb/Custom-Colorful-Enchantment/issues/1)

This was caused by bad LiteLoader installation, you should install LiteLoader & Optifine into mods folder and do not install it as a library. Tell him to only install Forge in HMCL and downloader LiteLoader into mods folder. 
I think it's important to tell launcher authors to put LiteLoader & OptiFine into mods folder if ppl selected to install them with Forge. （即“一键安装”）

**Comment by Ecdcaeb** [comment]
I will do a test.
