### ISSUE TITLE
ViaForge and MixinBooter

### ISSUE THREAD

**Issue by Yura64UA** [CleanroomMC/MixinBooter#90]
### General Information

configanytime, mixinbooter, betterfps, controllable, controlling, darkredstone, entityculling, fermiumasm, fermiumbooter, foamfix, fpsreducer, homoium, ksyxis, lagbgonrevived, nether api, particleculling, phosphorcrashfix, phosphor, optifine, randompatches, rawinput, spark, universaltweaks, viaforge
### Bug Description

MixinBooter crashes with ViaForge
### Steps to Reproduce

Just download both mods ig
### Expected Behavior

the game shouldn't crash when i use viaforge

**Comment by Yura64UA** [comment]
[latest.log](https://github.com/user-attachments/files/16501322/latest.log)

**Comment by KorewaLidesu** [comment]
Have you report to ViaForge first?

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaForge/issues/103

This isn't caused by neither ViaForge nor MixinBooter. I've used them together for years.

This might be cause by unsupported Fermium stuffs, whatever, you should do binary search:

Remove half of the existing mods and put them aside and repeat until problematic mod/s are found.

**Comment by Yura64UA** [comment]
it was randompatches
